name: Update HSR Wish Data

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    # 添加权限设置
    permissions:
      contents: write  # 授予写入权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data scraper
      run: python starrial.py --save
      
    - name: Commit and push changes
      # 使用 actions/github-script 替代原生 git 命令
      uses: actions/github-script@v6
      with:
        script: |
          // 设置 Git 用户信息
          await exec.exec('git', ['config', '--global', 'user.name', 'GitHub Actions'])
          await exec.exec('git', ['config', '--global', 'user.email', 'actions@users.noreply.github.com'])
          
          // 添加更改
          await exec.exec('git', ['add', 'data.json'])
          
          // 检查是否有更改
          const status = await exec.getExecOutput('git', ['status', '--porcelain'])
          if (status.stdout) {
            // 提交更改
            await exec.exec('git', ['commit', '-m', `Auto update data: ${new Date().toUTCString()}`])
            
            // 使用 GitHub Actions 的 token 推送
            await exec.exec('git', ['push'])
          } else {
            console.log('没有检测到文件变更')
          }
